name: Build and test

on:
  merge_group:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Handy for testing

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:


  build-quesma-docker-image:
    uses: ./.github/workflows/build-quesma-docker-image.yml

